# Generated by Django 6.0.6 on 2026-07-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='ai_suggestions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='resume',
            name='contact_info',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
