# Generated by Django 6.0.6 on 2026-07-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_resume_ai_suggestions_resume_contact_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='ats_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='resume',
            name='built_resume',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='resume',
            name='cover_letter',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='resume',
            name='fusion_analysis',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='resume',
            name='gemini_analysis',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='resume',
            name='grammar_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='resume',
            name='grok_analysis',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='resume',
            name='raw_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='resume',
            name='resume_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='resume',
            name='technical_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='resume',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='ai_suggestions',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
