# Generated by Django 6.0.6 on 2026-08-12 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0002_application_fusion_match_application_gemini_match_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_score', models.FloatField(default=0)),
                ('experience_score', models.FloatField(default=0)),
                ('education_score', models.FloatField(default=0)),
                ('semantic_score', models.FloatField(default=0)),
                ('preferred_skill_score', models.FloatField(default=0)),
                ('overall_score', models.FloatField(default=0)),
                ('matched_skills', models.JSONField(default=list)),
                ('missing_skills', models.JSONField(default=list)),
                ('explanation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match', to='applications.application')),
            ],
        ),
    ]
